{"name": "Проверка увелечения счетчика за сегодня", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:197:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:527:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16", "trace": "self = <tests.test_feed.TestFeedPage object at 0x7f6b9f549100>\ndriver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"dd5f3ca4-8a10-49d4-aa65-3fb7a47c54e2\")>\nuser = {'email': 'jvzdo@ya.ru', 'name': 'bmiolpzdfh', 'password': 'reagzudt'}\n\n    @title(\"Проверка увелечения счетчика за сегодня\")\n    def test_daily_counter(self, driver, user):\n        login_page = LoginPage(driver)\n        login_page.login(user[\"email\"], user[\"password\"])\n    \n        page = FeedPage(driver)\n        _, old_daily = page.get_orders_count()\n    \n        page = MainPage(driver)\n>       page.add_buns_to_order()\n\ntests/test_feed.py:59: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/main_page.py:42: in add_buns_to_order\n    self.wait_for_load_element(MainPageLocators.BUN_IN_ORDER)\npages/base_page.py:15: in wait_for_load_element\n    WebDriverWait(self.driver,TIMEOUT).until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"dd5f3ca4-8a10-49d4-aa65-3fb7a47c54e2\")>\nmethod = <function visibility_of_element_located.<locals>._predicate at 0x7f6b9f3c9040>, message = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            if time.monotonic() > end_time:\n                break\n            time.sleep(self._poll)\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:197:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:527:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n.venv/lib/python3.8/site-packages/selenium/webdriver/support/wait.py:105: TimeoutException"}, "steps": [{"name": "Логин пользователя", "status": "passed", "parameters": [{"name": "email", "value": "'jvzdo@ya.ru'"}, {"name": "password", "value": "'reagzudt'"}], "start": 1746969698837, "stop": 1746969699363}, {"name": "Получить количество заказов", "status": "passed", "start": 1746969700856, "stop": 1746969700920}, {"name": "Добавление булочки в заказ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:197:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:527:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"/home/marina/PycharmProjects/Diplom_3/.venv/lib/python3.8/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"/home/marina/PycharmProjects/Diplom_3/pages/main_page.py\", line 42, in add_buns_to_order\n    self.wait_for_load_element(MainPageLocators.BUN_IN_ORDER)\n  File \"/home/marina/PycharmProjects/Diplom_3/pages/base_page.py\", line 15, in wait_for_load_element\n    WebDriverWait(self.driver,TIMEOUT).until(\n  File \"/home/marina/PycharmProjects/Diplom_3/.venv/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1746969701391, "stop": 1746969712157}], "attachments": [{"name": "log", "source": "87fa7b04-e810-476e-a0b2-979fc156652c-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1746969697198, "stop": 1746969712158, "uuid": "b9183d5b-602e-4cae-bbb7-03c7076eae93", "historyId": "a2938139bee5527f1dd8a892925c04a9", "testCaseId": "3841eeb29125b24e9c8c329e1dfac1ca", "fullName": "tests.test_feed.TestFeedPage#test_daily_counter", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_feed"}, {"name": "subSuite", "value": "TestFeedPage"}, {"name": "host", "value": "ws"}, {"name": "thread", "value": "1038636-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_feed"}]}