{"name": "Проверка увелечения счетчика за всё время", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:197:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:527:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16", "trace": "self = <tests.test_feed.TestFeedPage object at 0x7f6b9f54daf0>\ndriver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"d345b812-2a26-4250-820a-626592ee10ec\")>\nuser = {'email': 'hodfk@ya.ru', 'name': 'conrcgkoex', 'password': 'uzfeowfx'}\n\n    @title(\"Проверка увелечения счетчика за всё время\")\n    def test_total_counter(self, driver, user):\n        login_page = LoginPage(driver)\n        login_page.login(user[\"email\"], user[\"password\"])\n    \n        page = FeedPage(driver)\n        old_total, _ = page.get_orders_count()\n    \n        page = MainPage(driver)\n>       page.add_buns_to_order()\n\ntests/test_feed.py:43: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/main_page.py:42: in add_buns_to_order\n    self.wait_for_load_element(MainPageLocators.BUN_IN_ORDER)\npages/base_page.py:15: in wait_for_load_element\n    WebDriverWait(self.driver,TIMEOUT).until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"d345b812-2a26-4250-820a-626592ee10ec\")>\nmethod = <function visibility_of_element_located.<locals>._predicate at 0x7f6b9f3c94c0>, message = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            if time.monotonic() > end_time:\n                break\n            time.sleep(self._poll)\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:197:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:527:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n.venv/lib/python3.8/site-packages/selenium/webdriver/support/wait.py:105: TimeoutException"}, "steps": [{"name": "Логин пользователя", "status": "passed", "parameters": [{"name": "email", "value": "'hodfk@ya.ru'"}, {"name": "password", "value": "'uzfeowfx'"}], "start": 1746969670855, "stop": 1746969671362}, {"name": "Получить количество заказов", "status": "passed", "start": 1746969672817, "stop": 1746969672884}, {"name": "Добавление булочки в заказ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:197:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:527:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"/home/marina/PycharmProjects/Diplom_3/.venv/lib/python3.8/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"/home/marina/PycharmProjects/Diplom_3/pages/main_page.py\", line 42, in add_buns_to_order\n    self.wait_for_load_element(MainPageLocators.BUN_IN_ORDER)\n  File \"/home/marina/PycharmProjects/Diplom_3/pages/base_page.py\", line 15, in wait_for_load_element\n    WebDriverWait(self.driver,TIMEOUT).until(\n  File \"/home/marina/PycharmProjects/Diplom_3/.venv/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1746969673376, "stop": 1746969684147}], "attachments": [{"name": "log", "source": "3c42d330-85e8-4acf-8a2b-e9409ab4404b-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1746969669343, "stop": 1746969684148, "uuid": "4b83c3a5-2c75-4aaa-9e5e-a285bcb3332c", "historyId": "cee9d68c9d7db8ad6d51fe83b194ea19", "testCaseId": "59f698ed5d7f56fe3d664ba4be3ab011", "fullName": "tests.test_feed.TestFeedPage#test_total_counter", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_feed"}, {"name": "subSuite", "value": "TestFeedPage"}, {"name": "host", "value": "ws"}, {"name": "thread", "value": "1038636-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_feed"}]}